Edit and delete messages
CS673S17-Team-3/Final_Project pull request #27
Opened 2017-04-12 17:03 UTC by CS673S17-Team-3

Hover over a message to show options to edit or delete it - only if it's your message. There's a smiley face there that can be used to implement reactions, but that is for another user story.

2017-04-15 14:12 UTC, oliver-nowak requested changes

2017-04-15 14:12 UTC, oliver-nowak commented on group1/comm/static/comm_tool.css
> +}*/
@CS673S17-Team-3 this commented code should be deleted.

2017-04-18 05:24 UTC, CS673S17-Team-3 commented on group1/comm/static/comm_tool.css
> +}*/
It has been removed!

2017-04-19 23:17 UTC, oliver-nowak approved these changes
LGTM

2017-04-22 19:37 UTC, merged